### ISSUE TITLE
Misconstructed path on dev server

### ISSUE THREAD

**Issue by ekafyi** [siverv/astro-lunr#1]
Hi, thanks for this plugin.

I have issue using it on dev. Exact same path config as the example; no customized astro config (from the default starter). This is the error on dev:

```
[vite] Internal server error: Could not find pre-built lunr-files - search is not available without first building your astro-pages at least once. Error: ENOENT: no such file or directory, stat '/FILESYSTEM_PROJECT_PATH/dist/lunr./index/idx.json'
```

There is an extra `.` after `lunr`, which caused the error. I "fixed" it locally by modifying this part: https://github.com/siverv/astro-lunr/blob/00a915fc838d1213904d4e69b02c025a7ceff64a/plugin.mjs#L67

```diff
- path = path.replace(base, "./");
+ path = path.replace(base, "/");
```

This did not occur on build & preview, everything works fine.

I dont know enough about the different use cases of custom path configs so dont feel comfortable making a PR, just thought i'd file this for others googling the error. I'm afraid i'm not able to make a reproduction yet for now, will post it when i'm free.

**Comment by siverv** [comment]
Thank you for describing the issue; I'll take a look.

Strange that I haven't encountered it myself, as I've used both with and without `base`. Either way, I was a bit too hasty on implementing the `base` part to make it work on github-pages, and that `path.replace` should be replaced with node's internal `path`-module or similar.

**Comment by siverv** [comment]
It should be fixed now.

The `req.url` should always start with `config.base` when using a base, so there never was any reason to work with relative paths.

**Comment by ekafyi** [comment]
yep, upgrading to 0.0.3 fixed it on my end!
awesome, thank you!
